Update: rock-paper-scissors example
martius-lab/teamproject-competition-server pull request #100
Opened 2024-03-08 13:35 UTC by SveaGaenzle

I updated the `rockpaperscissors` example to work with the refactored code.

## Issue:

- resolves #77 

## Description:
- I added a config file.
- I have updated the `RPSAgent` so that it always returns a random int between 0 and 2 as a step and prints the results at the end of the game. As in the other agents, you can also select a token from the four dummy users.
- I renamed the file `server` to `game` and refactored the code to work with the new version.

2024-03-08 21:19 UTC, Raining-Cloud requested changes

2024-03-08 21:19 UTC, Raining-Cloud commented on examples/rockpaperscissors/agent.py
> +RPSAgent = Agent()
RPSAgent is an object at this point it should be something like agent or so (see [here](https://google.github.io/styleguide/pyguide.html#s3.16-naming ))

2024-03-08 21:19 UTC, Raining-Cloud commented on examples/rockpaperscissors/game.py
> +class RPSServer(IGame):
This is the RPSGame not a server

2024-03-10 19:23 UTC, Cari1111 requested changes
Thank you for updating this example game! The game works correctly and the code is written well. I just have two little suggestions below.

2024-03-10 19:23 UTC, Cari1111 commented on examples/rockpaperscissors/game.py
> +        self.scores: dict[PlayerID, float] = {p.id: 0.0 for p in players}
This is unnecessary because `self.scores` is already initialized in this way.

2024-03-11 19:27 UTC, Cari1111 approved these changes
The changes I requested are correctly implemented and the game works!

2024-03-11 19:29 UTC, Raining-Cloud approved these changes
LGTM!

2024-03-11 19:47 UTC, merged